name: awesome-webvis ci

on:
  push:
  schedule:
     # 8pm CST is 2am UTC
     - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
